# Generated by Django 5.2.16 on 2026-07-10 07:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import school.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school_code",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("school_name", models.CharField(max_length=255, unique=True)),
                ("short_name", models.CharField(blank=True, max_length=50)),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[
                            django.core.validators.EmailValidator(
                                message="Enter a valid email address."
                            )
                        ],
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 10-digit phone number.",
                                regex="^\\d{10}$",
                            )
                        ],
                    ),
                ),
                (
                    "alternate_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 10-digit phone number.",
                                regex="^\\d{10}$",
                            )
                        ],
                    ),
                ),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(default="India", max_length=100)),
                ("pincode", models.CharField(max_length=12)),
                (
                    "board",
                    models.CharField(
                        choices=[
                            ("CBSE", "CBSE"),
                            ("ICSE", "ICSE"),
                            ("STATE_BOARD", "State Board"),
                            ("IB", "IB"),
                            ("CAMBRIDGE", "Cambridge"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "school_type",
                    models.CharField(
                        choices=[
                            ("PRIVATE", "Private"),
                            ("GOVERNMENT", "Government"),
                            ("SEMI_GOVERNMENT", "Semi Government"),
                        ],
                        max_length=30,
                    ),
                ),
                ("principal_name", models.CharField(max_length=150)),
                (
                    "principal_phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 10-digit phone number.",
                                regex="^\\d{10}$",
                            )
                        ],
                    ),
                ),
                (
                    "principal_email",
                    models.EmailField(
                        max_length=254,
                        validators=[
                            django.core.validators.EmailValidator(
                                message="Enter a valid email address."
                            )
                        ],
                    ),
                ),
                (
                    "attendance_threshold",
                    models.DecimalField(decimal_places=2, default=75.0, max_digits=5),
                ),
                (
                    "attendance_start_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "school_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="schools/logos/",
                        validators=[school.validators.validate_school_logo],
                    ),
                ),
                ("timezone", models.CharField(default="Asia/Kolkata", max_length=64)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admin_school",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schools_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schools_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["school_name"],
                "indexes": [
                    models.Index(
                        fields=["school_code"], name="school_scho_school__13936a_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="school_scho_is_acti_3637d4_idx"
                    ),
                    models.Index(
                        fields=["city", "state"], name="school_scho_city_4508a9_idx"
                    ),
                ],
            },
        ),
    ]
